### PR TITLE
Adding send with template method

### PR DESCRIPTION
**Pull request by singularity-is-i**

### CODE REVIEW

**Comment by jesse123green** [comment]
Are you planning to include this in a version soon? Would be great to have!

**Comment by singularity-is-i** [comment]
Hi Jesse,

I have already made the changes in my repo and I have been using it for one of my projects, it works like a charm.

https://github.com/singularity-is-i/pystmark

Check it out.

**Comment by feesh** [comment]
Hi @xsleonard! Any chance this can be merged into the main branch?

**Comment by xsleonard** [comment]
@feesh the tests are failing on pep8 checks

**Pull request closed without merging**
